apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
  namespace: adia
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: finance
          image: lpsouza/adia-finance-api:latest
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: finance
            - secretRef:
                name: finance
