name: Build and Publish to Docker Hub

on:
    push:
        branches: [main]
        paths-ignore:
            - "**/README.md"
            - "**/LICENSE"
            - "**/.editorconfig"
            - "**/.gitignore"
            - ".vscode/*"
    pull_request:
        branches: [main]
        paths-ignore:
            - "**/README.md"
            - "**/LICENSE"
            - "**/.editorconfig"
            - "**/.gitignore"
            - ".vscode/*"

jobs:
    test_suite:
        name: Run tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.13]
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm install
            - run: npm test
    build_and_publish:
        name: Build and Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        needs:
            - test_suite
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v2
              id: buildx

            - name: Avaliable platforms
              run: echo ${{ steps.buildx.outputs.platforms }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  platforms: "linux/amd64, linux/arm64"
                  context: .
                  push: true
                  tags: "lpsouza/adia-finance-api:latest"
